---
version: "3.8"

services:
  db:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      target: builder
      args:
        DEV: true
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - /app/.venv
